# Generated by Django 5.1 on 2024-08-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_banner_image_homepage_body_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Admin',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='author',
            new_name='admin',
        ),
    ]
